name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 2.2.0
homepage: https://jesway.com
repository: https://github.com/Jesway/Flutter-Translate-Gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.4.0
  async: ^2.8.2
  build: ^2.1.1
  code_builder: ^4.1.0
  dart_casing: ^2.0.0
  dart_style: ^2.0.0
  dart_utils: ^2.0.0
  flutter_translate_annotations: ^2.1.0
  glob: ^2.0.2
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.5
